# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-17 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('resolve_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='No', max_length=4)),
                ('finish', models.CharField(default='No', max_length=4)),
                ('invested_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'ordering': ['add_time', 'status'],
            },
        ),
    ]
