# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-12 09:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='resolve_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
